### ISSUE TITLE
v1.1.0 options.name is failure

### ISSUE THREAD

**Issue by lincenying** [webpack-contrib/url-loader#138]
This is my configuration file

```
{
                test: /\.(png|jpe?g|gif|svg)(\?.*)?$/,
                use: [
                    {
                        loader: 'url-loader',
                        options: {
                            name: 'img/[name].[hash:7].[ext]',
                            limit: 8192
                        }
                    }
                ]
            },
```

This is the generated file

![image](https://user-images.githubusercontent.com/10840991/44128507-f3850806-a075-11e8-8f0b-7ead4475bef4.png)

v1.0.1 is ok

![image](https://user-images.githubusercontent.com/10840991/44128559-39fd7d04-a076-11e8-9b46-63ad13abf04f.png)

**Comment by insin** [comment]
Confirming the same issue, looks like `name` isn't getting passed along to the fallback.

![conemu64_2018-08-15_13-40-59](https://user-images.githubusercontent.com/226692/44130827-bde1ba1a-a092-11e8-9f95-9b4a02540e02.png)

**Comment by insin** [comment]
I think it's because v1.0.1 used to do this, so `file-loader` would pick up all the given options:

```js
const fallback = require(options.fallback ? options.fallback : 'file-loader');
return fallback.call(this, src);
```

Here's a failing test for `fallback.test.js` showing failure to pass on the `name` option:

```js
    test('{String}', async () => {
      const config = {
        loader: {
          test: /\.png$/,
          options: {
            limit: 100,
            name: 'name-for-url-loader.[ext]',
          },
        },
      };

      const stats = await webpack('fixture.js', config);
      const { source } = stats.toJson().modules[0];

      expect(source).toMatchSnapshot();
    });
```

For this not to be a breaking release, would it need to support passing along all the [options` file-loader` can take](https://github.com/webpack-contrib/file-loader#options), or do what it used to do if a fallback or its options aren't explicitly configured?

**Comment by hxlniada** [comment]
this is a big bug
