### ISSUE TITLE
Incorrect peer dependency warning

### ISSUE THREAD

**Issue by andrioli** [webpack-contrib/url-loader#142]
I upgraded from `1.0.1` to `1.1.0` and the following warn message pop up during `yarn install` command.

```
warning " > url-loader@1.1.0" has incorrect peer dependency "webpack@^4.0.0".
```

I'm using Webpack 3. The plugin isn't intent to work safely with Wabpack 3 anymore? If it should work fine why not update the peer dependencies to include webpack 3 as well?

**Comment by michael-ciniawsky** [comment]
Feel free to send a PR relaxing/removing the `peerDependency`, the loader should work perfectly with webpack =< v3.0.0` :)

**Comment by evilebottnawi** [comment]
@michael-ciniawsky we support only `webpack@4` because in some cases loader(s) can doesn't work with `webpack@3`, also `webpack@3` deplrecated. Don't accept PR with backward compatobility with `webpack@3`.

@andrioli https://github.com/webpack-contrib/url-loader#requirements Please upgrade you webpack version or use old `url-loader` version. Thanks!

**Comment by andrioli** [comment]
> Feel free to send a PR relaxing/removing the peerDependency

I was about to create a PR. But I preferred to ask if its okay to use Webpack 3 before

> Or is something not working for you besides the warning 

Working perfectly, no problems found so far

> we support only webpack@4 because in some cases loader(s) can doesn't work with webpack@3 as expected, also webpack@3 deplrecated.

😩 That's Okay!

> ... Please upgrade you webpack version or use old `url-loader` version. Thanks!

I didn't notice this message in the beginning of the page.  Sorry about the noise.

I know Webpack 3 is deprecated. But we are nor planning major updates right now, so I will downgrade `url-loader`.

Thanks for the fast support!

**Comment by michael-ciniawsky** [comment]
@evilebottnawi It was introduced by https://github.com/webpack-contrib/url-loader/commit/9946374885ec01578ad692a386c82e08b3a9c1e7 in released as a minor and I think it should be 'reverted', there is no need to be strict here since no breaking changes to the Loader API where introduced between `webpack v3.0.0...4.0.0` that affected  the `url-loader` directly

@andrioli Sry 😞
