### ISSUE TITLE
how to override publicPath in url-loader

### ISSUE THREAD

**Issue by TonyLuo** [webpack-contrib/url-loader#90]
**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**
I am trying to set relative path for publicPath to be "./", in case the application is not a root application in tomcat.

      {
        test: /\.(woff2?|eot|ttf|otf)(\?.*)?$/,
        loader: 'url',
        query: {
          limit: 10000,
          name: utils.assetsPath('fonts/[name].[hash:7].[ext]')
        },
        options: {
          publicPath: '/'
        }
      }
``
the folder structure is 
![image](https://user-images.githubusercontent.com/3250305/30980583-33ea1bf6-a447-11e7-9a37-d2ef74e3c69a.png)

but in the file app.cb88ff13db03d707b61629284577bf4c.css, it refer to current folder to search the fonts. Is any option to override the publicPath for the url-loader  ?

``
@font-face{font-family:FontAwesome;src:url(./static/fonts/fontawesome-webfont.674f50d.eot)
``
**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**Please mention other relevant information such as your webpack version, Node.js version and Operating System.**

**Comment by michael-ciniawsky** [comment]
Use the [`file-loader`](https://github.com/webpack-contrib/file-loader) directly instead or ensure that the `limit` is reached for all your fonts. Otherwise they will be inline as `base64` encoded BLOB into your CSS

**Comment by ljwagerfield** [comment]
I disagree with the workaround (please correct me if I'm wrong!)...

Without being able to set `publicPath` means any path `url-loader` generates will be wrong... meaning we have to set `limit` to `0` since if it ever produced a path, it would be incorrect.

Would it be possible to bring this module inline with `file-loader` in this respect, since the behaviour of this loader is effectively "a decorator that falls back onto `file-loader` if the `limit` is reached".
